### ISSUE TITLE
Design logo ,Search and Save related images and icons for the project

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#11]
### **Subtasks**

- [x] Search for royalty free images using [https://www.pexels.com/](url)
- [x] search for the icons from [https://www.iconfinder.com/](url)
- [x] Design logo for the website [https://www.canva.com/](url)
- [x] adjust the sizing of images. 
  
_decided to design LOGO which should be simple yet eye catching..._
### **logo designed**
![Image](https://github.com/user-attachments/assets/7ca832c3-2060-4a86-8b07-182a5806c843) ![Image](https://github.com/user-attachments/assets/dadc7bc1-1465-461d-8f00-620db832daa0)
![Image](https://github.com/user-attachments/assets/f68a337b-6f96-4a2f-82e2-ddc1046b5a8c) ![Image](https://github.com/user-attachments/assets/c7703d28-f780-4465-97e4-fbae3a50876c)

### **logo selected**

![Image](https://github.com/user-attachments/assets/4c767414-7f49-49fe-ae0b-8dc74902c9ba)
