### ISSUE TITLE
Review API Documentation

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#12]
### **Subtasks**

- [x] Review the API endpoints provided in the documentation.
- [x] Review the API endpoints for blog posts (GET, POST, PUT, DELETE).
- [x]  Verify if any authentication tokens or headers are needed for API calls.
- [x] Read API documentation for authentication (register/login).
- [x] Identify which endpoints are needed for each feature (e.g., GET for fetching blog posts, POST for creating posts).
- [x] Make notes on required parameters, expected responses, and any authentication needed.
 
https://v2.api.noroff.dev/docs/static/index.html#/blog-posts/post_blog_posts__name_
https://docs.noroff.dev/docs/v2/blog/posts
