### ISSUE TITLE
Set Up Development Environment

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#14]
### **Subtasks**

- [x] Set up the project folder structure (e.g., index.html, styles, scripts, assets).
- [x] Test the development environment by creating a simple HTML page and previewing it locally.
- [x] add Readme file and search how to write on readme and what to write.
