### ISSUE TITLE
Plan the CSS Structure for Each Page

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#16]
### **Subtasks**

- [x] Based on wireframes and mockups , outline the HTML structure for each page add styling .
- [x] create clean styling.
- [x] create a global.css to add the repeatative styles.
- [x] List the main sections and elements for each page (e.g., header, main content, footer) .
