### ISSUE TITLE
Create Login Form with Token Management

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#17]
### **subtasks**

- [x] Create the login form (email, password).
- [x] Send a POST /auth/login request to get an authentication token.
- [x] Store the token in the browser's local storage for session management.
- [x] Redirect the user to the admin pages after successful login.
