### ISSUE TITLE
Create Registration Form

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#18]
**Subtasks**

- [x] Create the registration form (name, email, password).
- [x] Send a POST /auth/register request to create a new account.
- [x] Display success or error messages based on the registration response.
- [x] Redirect the user to the login page after successful registration.
