### ISSUE TITLE
Implement API Integration for Blog Feed

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#19]
**Subtasks**

- [x]  Set up a JavaScript function to fetch blog posts using GET /blog/posts/<name>.
- [x]  Display the blog post data in a static grid layout (12 posts).
- [x]  Handle errors in fetching the data and display fallback content.
- [x] Test the API call and verify if the blog posts appear correctly.
