### ISSUE TITLE
Accept GitHub Classroom Brief and Clone the Repository

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#2]
### **Subtasks**

- [x] Log in to GitHub Classroom and accept the project brief.
- [x] Clone the repository to your local machine using GitHub Desktop.
- [x] Verify that the repository is cloned correctly and commit an initial "setup" commit.
