### ISSUE TITLE
Create Carousel for Latest Blog Posts

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#20]
**Subtasks**

- [x]  Design the HTML structure for the carousel.
- [x] Add JavaScript to rotate the 3 latest blog posts.(slice function)
- [x] Implement "Next" and "Previous" buttons to navigate between posts.
- [x] Ensure the carousel loops back to the first post after reaching the end.
