### ISSUE TITLE
Link Carousel to Blog Post Pages

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#21]
**Subtasks**

- [x] Add clickable buttons for each carousel item.
- [x] Pass the blog post ID in the URL to the blog post page.
- [x] Ensure each blog post page dynamically fetches and displays content.
- [x] Test the linking mechanism across multiple blog posts.
