### ISSUE TITLE
Testing and Debugging

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#22]
**Subtasks**

- [ ] Test all user stories to ensure correct functionality.
- [ ] Manually test the blog feed page for API integration.
- [ ] Test the authentication flow for login and registration.
- [ ] Debug and fix any issues that arise during testing.
