### ISSUE TITLE
Implement Pagination or Sorting Feature (optional)

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#23]
**Subtasks**

- [x] Add pagination controls to navigate through blog post pages.
- [x] Fetch and display the next set of blog posts upon clicking pagination controls.
- [x] Implement sorting functionality to order posts by date or title.
- [x]  Test both pagination and sorting mechanisms.
