### ISSUE TITLE
Develop Blog Post Public Page

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#29]
**Subtasks**

- [x] Create HTML structure for the blog post page (title, date, content).
- [x] Fetch the blog post using GET /blog/posts/<name>/<id>.
- [x]  Display the blog post's title, date, image, and content dynamically.
- [x] Handle errors and ensure the page displays appropriate error messages.
