### ISSUE TITLE
Create a Project Plan Using GitHub Projects

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#3]
### **Subtasks**

- [x] Open GitHub and create a new project board.
- [x] Set up columns for “To Do,” “In Progress,” and “Done.”
- [x] Break down the main project tasks into smaller tasks and add them to the “To Do” column.
- [x] Assign estimated timelines and priorities to each task.
- [x] Link user stories to specific tasks to ensure all requirements are covered.

P.S i will update time to time as  not sure about api yet!
