### ISSUE TITLE
Create a create post button attached to the create post page

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#30]
**Subtasks**

- [x] Add the button to the desired location in the blog feed page visible to only users who signed in .
- [x] Test the HTML page to ensure the button is visible and links to the correct page.
- [x] Style the button (e.g., background color, padding, border-radius).
- [x] Add an event listener to handle the click event for the button.
- [x] Add logic to check if the user is authenticated (check if an auth token exists in localStorage).
- [x] Test the functionality by simulating different scenarios (authenticated vs. unauthenticated users).
- [x] Verify that clicking the button successfully navigates to the "create-post.html" page.
