### ISSUE TITLE
Research Responsive Web Design Best Practices

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#47]
### **Subtasks**

- [x] Research best practices for responsive design and note key principles (e.g., mobile-first design, media queries).
- [x] Look for inspiration and examples of responsive web applications in a similar domain.
- [x] Document findings and list techniques to be used in the project .
- [x] Research similar projects like blogs.
- [x] Find related videos in building similar projects. 

### Some examples i liked the most during research of similar blogs that i want to design;
[https://www.hellohydrangea.com/blog/](url)
[https://www.brewdrkombucha.com/blog](url)
[https://cassandralavalle.com/blog/](url)
[https://www.oldbrandnew.com/blog](url)
[https://www.verbproducts.com/blogs/verb-word](url)
