### ISSUE TITLE
Create a Manage Post page

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#48]
### **Subtasks**

- [x] its very important to understand the UI 
- [x] Create Post Cards with functionality
- [x] Create buttons like Edit + Delete + view (optional)
- [x] Include URL Title and buttons 
- [x] Create a create post button to create  anew post
