### ISSUE TITLE
Required Deliverables

### ISSUE THREAD

**Issue by sanakhuram** [sanakhuram/FED-PE1-SanaKhuram-color-muse-blog-#49]
**Subtasks**

**Required Deliverables**

- [x] Link to GitHub classroom repository
- [x] Link to public hosted demo
- [x] Link to Figma design assets
- [x] Link to public planning board
- [x] Login details for the admin user (email and password)
